version: '3.2'
volumes:
  postgres-data:
services:

  database:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  greenfy:
    build:
      context: .
      dockerfile: Dockerfile
    command: mix phx.server
    depends_on:
      - database
    ports:
      - "4000:4000"
    volumes:
      - .:/greenfy
      - /greenfy/assets/node_modules
